name: DwarvenLockup
main: me.matthijs110.DwarvenLockup.Main
version: 1.0
author: matthijs110

commands:
  prison:
     description: teleports you to a Prison
  shop:
     description: teleports you to the prison shop